### ISSUE TITLE
修改拼音命名方式

### ISSUE THREAD

**Issue by SnowWarri0r** [Harper-Ge/The-star#1]
问题举例：
```css
#zhuye{
    background: url(../../img/zhuyebtn.png) no-repeat;
    background-size: 100%;
    left: 9.74%;
    right: 83.71%;
    top: 90.52%;
    bottom: 6.46%;
}
#shequ{
    background: url(../../img/shequbtn.png) no-repeat;
    background-size: 100%;

}
#wode{
    background: url(../../img/wodebtn.png) no-repeat;
    background-size: 100%;
}
#geren{
    background: url(../../img/gerenbtn.png) no-repeat;
    background-size: 100%;
```
```html
 <div id='bottom-box'>
                <div className='small-box'><button id='zhuye'></button><span>主页</span></div>
                <div className='small-box'><button id='shequ'></button><span>社区</span></div>
                <div className='small-box'><button id='wode' ></button><span>我的</span></div>
                <div className='small-box'><button id='geren'></button><span>个人</span></div>
            </div>
```
如上的`zhuye`,`shequ`等可修改成`homeBtn`或`homeButton`，`shequ`可修改为`communityBtn`等
